default_agent: agent
agents:
  agent:
    name: cloud_agent_core
    entrypoint: agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::354334841216:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-49c9457227
      execution_role_auto_create: false
      account: '354334841216'
      region: ap-southeast-2
      ecr_repository: 354334841216.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-cloud_agent_core
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: cloud_agent_core-r7Zv5dCMwl
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:354334841216:runtime/cloud_agent_core-r7Zv5dCMwl
      agent_session_id: d8581123-d0c9-4793-8189-f242b67dcda1
    codebuild:
      project_name: bedrock-agentcore-cloud_agent_core-builder
      execution_role: arn:aws:iam::354334841216:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-49c9457227
      source_bucket: bedrock-agentcore-codebuild-sources-354334841216-ap-southeast-2
    authorizer_configuration: null
    oauth_configuration: null
  cloud_agent_core:
    name: cloud_agent_core
    entrypoint: agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::354334841216:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-49c9457227
      execution_role_auto_create: false
      account: '354334841216'
      region: ap-southeast-2
      ecr_repository: 354334841216.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-cloud_agent_core
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: cloud_agent_core-r7Zv5dCMwl
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:354334841216:runtime/cloud_agent_core-r7Zv5dCMwl
      agent_session_id: d8581123-d0c9-4793-8189-f242b67dcda1
    codebuild:
      project_name: bedrock-agentcore-cloud_agent_core-builder
      execution_role: arn:aws:iam::354334841216:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-49c9457227
      source_bucket: bedrock-agentcore-codebuild-sources-354334841216-ap-southeast-2
    authorizer_configuration: null
    oauth_configuration: null
